package org.angelssoftware.interfaces;

import org.angelssoftware.interfaces.readonly.RobotPropertiesInterfaceReadOnly;
import org.angelssoftware.interfaces.writeonly.RobotPropertiesInterfaceWriteOnly;

public interface RobotPropertiesInterface extends RobotPropertiesInterfaceReadOnly, RobotPropertiesInterfaceWriteOnly{

}
